/**
 * braid-trace-monoid.test.ts — what the braid's history ACTUALLY is, checked
 * exhaustively against the implementation rather than asserted in a comment.
 *
 * ══ THE OBJECT ══
 *
 * The design notes call the history "a product of free monoids". That is a
 * description of the representation, not an identification of the object. The
 * object has a name and a literature: it is a MAZURKIEWICZ TRACE MONOID.
 *
 *   M(Σ, I) = Σ* / ≡
 *
 * where Σ is the alphabet of messages, and I ⊆ Σ×Σ is an irreflexive symmetric
 * INDEPENDENCE relation, and ≡ is the congruence generated by
 *
 *   ab ≡ ba   for all (a,b) ∈ I
 *
 * The braid instantiates this with exactly one choice:
 *
 *   (m, m') ∈ I  ⟺  seat(m) ≠ seat(m')
 *
 * Messages from one seat are DEPENDENT: totally ordered by seq, they may never
 * be transposed. Messages from different seats are INDEPENDENT: they commute,
 * which is precisely the property that lets the circle run with no sequencer.
 * The dependence relation D = Σ×Σ \ I is an equivalence here (same-seat), which
 * makes this the well-studied special case of a DIRECT PRODUCT of free monoids —
 * so the earlier description was right, but as a consequence rather than a
 * definition, and the consequence is what makes the design correct.
 *
 * ══ THE TOWER ══
 *
 *   Σ*        free monoid. A total order on all messages. What a server gives
 *             you, and what the braid deliberately refuses to require.
 *    ↓  quotient by I  (transpose independent adjacent letters)
 *   M(Σ,I)    trace monoid. THE BRAID'S ACTUAL HISTORY.
 *    ↓  quotient by full commutativity (make every pair independent)
 *   ℕ^Σ       Parikh image / abelianization. THE COUNT MODEL.
 *
 * The thesis correction that produced this code was exactly the observation that
 * key derivation had been reading the BOTTOM of the tower when it needed the
 * MIDDLE. This file pins that: it measures the kernel of each map, exhaustively.
 *
 * ══ THE THEOREM BEING RELIED ON ══
 *
 * PROJECTION LEMMA (trace theory). Two traces are equal iff their projections
 * onto every dependence class are equal. Here the dependence classes are the
 * seats, so a trace is DETERMINED BY ITS PER-SEAT SEQUENCES and nothing else.
 *
 * That is why `transcriptCommit(heads)` is sound: hashing the per-seat chain
 * heads is hashing the complete projection family, which by the lemma is a
 * faithful invariant of the trace. Not a heuristic — a normal form.
 *
 * ══ WHAT MUST BE TRUE ══
 *
 *   SOUNDNESS     ≡-equal words ⟹ equal commitment.
 *                 Without it the circle cannot converge: two members who
 *                 received the same messages in different orders would derive
 *                 different keys and the group would silently split.
 *
 *   COMPLETENESS  ≢-distinct traces ⟹ distinct commitment.
 *                 Without it two genuinely different histories derive the SAME
 *                 key, which is the property whose absence made the count digest
 *                 unusable for keying.
 *
 * The invariant the braid needs is one whose kernel is EXACTLY the trace
 * congruence. Coarser is insecure. Finer breaks convergence. Both directions are
 * checked below, by enumeration rather than by argument.
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { transcriptCommit, extendStrand } from "../../src/scripts/whisper/live-braid.js";
import { loopInit, loopTrain, modelDigest, type ModelCounts } from "../../src/scripts/whisper/live-loop.js";
import { deterministicBytes } from "./_helpers/generators.js";
import { toHex } from "../../src/scripts/whisper/wasm.js";

/** a message: which seat said it, and what it said. */
interface Msg { seat: number; body: Uint8Array }

/** fold a word into per-seat chain heads, exactly as braidOpen does. */
async function commitOf(word: Msg[], seats: number): Promise<string> {
  const heads: Uint8Array[] = Array.from({ length: seats }, () => new Uint8Array(32));
  for (const m of word) heads[m.seat] = await extendStrand(heads[m.seat], m.seat, m.body);
  return toHex(await transcriptCommit(heads));
}

/** fold a word into the count model, exactly as the membrane does. */
const LOOP_BLOCK = deterministicBytes(65536, 0x7ACE0001);

async function parikhOf(word: Msg[]): Promise<string> {
  const base = loopInit(LOOP_BLOCK);
  const counts: ModelCounts = {
    countsBitM: base.countsBitM, countsBit1: base.countsBit1, countsBitX: base.countsBitX,
  };
  for (const m of word) loopTrain(counts, m.body);
  return toHex(await modelDigest(counts));
}

/**
 * Every LINEAR EXTENSION of a trace: all interleavings that respect each seat's
 * internal order while allowing any interleaving across seats. This enumerates
 * the ≡-class of a word — the fibre of the quotient map Σ* → M(Σ,I).
 */
function linearExtensions(perSeat: Uint8Array[][]): Msg[][] {
  const out: Msg[][] = [];
  const taken = perSeat.map(() => 0);
  const total = perSeat.reduce((n, s) => n + s.length, 0);
  const current: Msg[] = [];

  const walk = (): void => {
    if (current.length === total) { out.push(current.slice()); return; }
    for (let seat = 0; seat < perSeat.length; seat++) {
      const i = taken[seat];
      if (i >= perSeat[seat].length) continue;
      current.push({ seat, body: perSeat[seat][i] });
      taken[seat]++;
      walk();
      taken[seat]--;
      current.pop();
    }
  };
  walk();
  return out;
}

/** (Σ nᵢ)! / Π nᵢ! — the size of a ≡-class, as combinatorics predicts it. */
function multinomial(sizes: number[]): number {
  const fact = (n: number): number => (n <= 1 ? 1 : n * fact(n - 1));
  return fact(sizes.reduce((a, b) => a + b, 0)) / sizes.reduce((a, n) => a * fact(n), 1);
}

const B = (...bytes: number[]) => Uint8Array.from(bytes);

describe("the braid's history is a Mazurkiewicz trace monoid", () => {
  describe("SOUNDNESS: the commitment is constant on a ≡-class", () => {
    it("every interleaving of 3 seats yields one commitment, and the class size matches theory", async () => {
      const perSeat = [
        [B(10, 11), B(12, 13)],
        [B(20, 21), B(22, 23)],
        [B(30, 31), B(32, 33)],
      ];
      const words = linearExtensions(perSeat);

      // the fibre size is combinatorial, so a bug in the enumerator cannot hide
      assert.equal(words.length, multinomial([2, 2, 2]),
        "enumerator must produce exactly 6!/(2!2!2!) = 90 linear extensions");
      assert.equal(words.length, 90);

      const commits = new Set<string>();
      for (const w of words) commits.add(await commitOf(w, 3));

      assert.equal(commits.size, 1,
        `all ${words.length} interleavings of one trace must commit identically; got ${commits.size}. ` +
        `Any spread here means two members who saw the same messages in different orders derive ` +
        `different keys, which is a silent group split.`);
    });

    it("holds for ragged strands too, where the class is much larger", async () => {
      const perSeat = [
        [B(1), B(2), B(3), B(4)],
        [B(5)],
        [B(6), B(7)],
      ];
      const words = linearExtensions(perSeat);
      assert.equal(words.length, multinomial([4, 1, 2]));   // 7!/(4!1!2!) = 105

      const commits = new Set<string>();
      for (const w of words) commits.add(await commitOf(w, 3));
      assert.equal(commits.size, 1, `${words.length} extensions, ${commits.size} commitments`);
    });
  });

  describe("COMPLETENESS: the commitment separates distinct traces", () => {
    it("is injective over an exhaustive space of traces", async () => {
      // Every assignment of a 2-letter alphabet to 2 seats x 2 positions:
      // 2^4 = 16 distinct traces, each of which must get its own commitment.
      const alphabet = [B(0xAA), B(0xBB)];
      const traces: Uint8Array[][][] = [];
      for (let a0 = 0; a0 < 2; a0++)
        for (let a1 = 0; a1 < 2; a1++)
          for (let b0 = 0; b0 < 2; b0++)
            for (let b1 = 0; b1 < 2; b1++)
              traces.push([[alphabet[a0], alphabet[a1]], [alphabet[b0], alphabet[b1]]]);

      const commits = new Set<string>();
      for (const t of traces) commits.add(await commitOf(linearExtensions(t)[0], 2));

      assert.equal(commits.size, traces.length,
        `${traces.length} distinct traces must yield ${traces.length} distinct commitments, ` +
        `got ${commits.size}. A collision here is two different histories deriving one key.`);
    });

    it("ORDER WITHIN a strand is committed, which is the whole point", async () => {
      // The one transposition the trace monoid FORBIDS: same seat, swapped order.
      // If this collides, the quotient is too coarse and the monoid is free
      // abelian rather than partially commutative.
      const forward = await commitOf([
        { seat: 0, body: B(1) }, { seat: 0, body: B(2) },
      ], 2);
      const backward = await commitOf([
        { seat: 0, body: B(2) }, { seat: 0, body: B(1) },
      ], 2);
      assert.notEqual(forward, backward,
        "transposing two messages of the SAME seat must change the commitment: " +
        "same-seat letters are dependent, so they do not commute");
    });

    it("WHICH SEAT spoke is committed, so strands cannot be transposed wholesale", async () => {
      const asSeat0 = await commitOf([{ seat: 0, body: B(9) }], 2);
      const asSeat1 = await commitOf([{ seat: 1, body: B(9) }], 2);
      assert.notEqual(asSeat0, asSeat1,
        "the same words from a different seat is a different trace");
    });
  });

  describe("THE TOWER: measuring the kernel of each quotient", () => {
    it("the Parikh image collapses traces the transcript separates, and here is a witness", async () => {
      /**
       * The explicit element of ker(Parikh) \ ker(transcript).
       *
       * countsBit1 records the multiset of (prev>>>4, byte) pairs, so two
       * plaintexts that are Eulerian-trail transpositions of the same bigram
       * graph produce IDENTICAL counts. This pair was found by exhaustive search
       * over 5-byte strings and is the smallest such witness.
       */
      const w1: Msg[] = [{ seat: 0, body: B(0x00, 0x01, 0x00, 0x02, 0x00) }];
      const w2: Msg[] = [{ seat: 0, body: B(0x00, 0x02, 0x00, 0x01, 0x00) }];

      assert.equal(await parikhOf(w1), await parikhOf(w2),
        "precondition: these two must be Parikh-equivalent, or the witness is stale");
      assert.notEqual(await commitOf(w1, 1), await commitOf(w2, 1),
        "the transcript must separate what the count model merges — this is exactly " +
        "the gap that made the count digest unusable for key derivation");
    });

    it("quantifies the collapse: |Σ*| > |M(Σ,I)| > |ℕ^Σ| on a real enumeration", async () => {
      // 2 seats x 2 messages, alphabet {0x00, 0x01}, bodies of length 2 so the
      // bigram model has something to merge.
      const alpha = [B(0x00, 0x01), B(0x01, 0x00)];
      const traces: Uint8Array[][][] = [];
      for (const a0 of alpha) for (const a1 of alpha)
        for (const b0 of alpha) for (const b1 of alpha)
          traces.push([[a0, a1], [b0, b1]]);

      let words = 0;
      const commits = new Set<string>();
      const pariks = new Set<string>();
      for (const t of traces) {
        const exts = linearExtensions(t);
        words += exts.length;
        for (const w of exts) {
          commits.add(await commitOf(w, 2));
          pariks.add(await parikhOf(w));
        }
      }

      // Σ* level: every interleaving of every trace is a distinct WORD
      assert.equal(words, traces.length * multinomial([2, 2]));

      // M(Σ,I) level: the transcript sees exactly the traces, no more, no less
      assert.equal(commits.size, traces.length,
        `transcript must resolve exactly the ${traces.length} traces, saw ${commits.size}`);

      // ℕ^Σ level: the count model sees strictly fewer
      assert.ok(pariks.size < commits.size,
        `the Parikh image must be a STRICT quotient (traces ${commits.size}, ` +
        `parikh classes ${pariks.size}); if these are equal the witness space is too small ` +
        `to exhibit the collapse and this test proves nothing`);

      // and the tower is strict at both steps
      assert.ok(words > commits.size, `words ${words} must exceed traces ${commits.size}`);
    });
  });

  describe("the design consequence, stated as a test", () => {
    it("the transcript's kernel is the trace congruence: neither coarser nor finer", async () => {
      // FINER would break convergence: some ≡-equal pair separated.
      const perSeat = [[B(1), B(2)], [B(3), B(4)]];
      const exts = linearExtensions(perSeat);
      const inClass = new Set<string>();
      for (const w of exts) inClass.add(await commitOf(w, 2));
      assert.equal(inClass.size, 1, "not finer: every linear extension agrees");

      // COARSER would break security: some ≢-distinct pair merged. Walk every
      // single-letter mutation and confirm each one moves the commitment.
      const base = await commitOf(exts[0], 2);
      for (let seat = 0; seat < 2; seat++) {
        for (let pos = 0; pos < 2; pos++) {
          const mutated = perSeat.map((s) => s.slice());
          mutated[seat][pos] = B(0xFF);
          const moved = await commitOf(linearExtensions(mutated)[0], 2);
          assert.notEqual(moved, base,
            `not coarser: changing seat ${seat} position ${pos} must move the commitment`);
        }
      }
    });
  });
});
